---
# CATALINA_BASE is the instance directory
- name: CATALINA_BASE dirs (root owned)
  become: true
  file:
    path: "{{ tomcat_catalina_base ~ '/' ~ item }}"
    owner: "root"
    group: "{{ tomcat_group }}"
    mode: "u=rwx,g=rx,o="
    state: directory
  with_items:
    - ""
    - "bin"
    - "conf"
    - "conf/Catalina"            # assumes engine name is catalina
    - "conf/Catalina/localhost"  # assumes virtual host is localhost
    - "lib"
    - "lib/org"
    - "lib/org/apache"
    - "lib/org/apache/catalina"
    - "lib/org/apache/catalina/util"
    - "shared"
    - "shared/classes"
    - "shared/lib"
  notify: Restart Tomcat

- name: CATALINA_BASE dirs (tomcat owned)
  become: true
  file:
    path: "{{ tomcat_catalina_base ~ '/' ~ item }}"
    group: "{{ tomcat_group }}"
    owner: "{{ tomcat_user }}"
    mode: "u=rwx,g=rx,o="
    state: directory
  with_items:
    - "logs"
    - "temp"
    - "webapps"
    - "work"
  notify: Restart Tomcat

- name: Tomcat Configuration (server.xml)
  become: true
  template:
    src: "{{ tomcat_server_xml_template }}"
    dest: "{{ tomcat_catalina_base ~ '/conf/server.xml' }}"
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  when: tomcat_server_xml_template is defined
  notify: Restart Tomcat

- name: Tomcat Configuration (web.xml)
  become: true
  template:
    src: "{{ tomcat_web_xml_template }}"
    dest: "{{ tomcat_catalina_base ~ '/conf/web.xml' }}"
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  when: tomcat_web_xml_template is defined
  notify: Restart Tomcat

- name: Tomcat Configuration (context.xml)
  become: true
  template:
    src: "{{ tomcat_context_xml_template }}"
    dest: "{{ tomcat_catalina_base ~ '/conf/context.xml' }}"
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  when: tomcat_context_xml_template is defined
  notify: Restart Tomcat

- name: Tomcat Configuration (common, if not present)
  become: true
  copy:
    src: "{{ tomcat_catalina_home ~ '/' ~ item }}"
    dest: "{{ tomcat_catalina_base ~ '/' ~ item  }}"
    remote_src: true
    force: false
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  with_items:
    - conf/catalina.policy
    - conf/catalina.properties
    - conf/context.xml
    - conf/server.xml
    - conf/tomcat-users.xml
    - conf/tomcat-users.xsd
    - conf/web.xml
  notify: Restart Tomcat

- name: Tomcat Configuration 8.5/9 (if not present)
  become: true
  copy:
    src: "{{ tomcat_catalina_home ~ '/' ~ item }}"
    dest: "{{ tomcat_catalina_base ~ '/' ~ item }}"
    remote_src: true
    force: false
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  with_items:
    - conf/jaspic-providers.xml
    - conf/jaspic-providers.xsd
  when: "(tomcat_version is version_compare('8.5.0','>='))"
  notify: Restart Tomcat

- name: Tomcat Logging Configuration (if log4j2 not enabled)
  become: true
  copy:
    src: "{{ tomcat_catalina_home ~ '/conf/logging.properties' }}"
    dest: "{{ tomcat_catalina_base ~ '/conf/logging.properties' }}"
    remote_src: true
    force: false
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
  when: not (tomcat_log4j2_enable | bool)
  notify: Restart Tomcat

- name: Shared Classloader
  become: true
  lineinfile:
    dest: "{{ tomcat_catalina_base ~ '/conf/catalina.properties' }}"
    backrefs: true
    group: "{{ tomcat_group }}"
    owner: "root"
    mode: "u=rw,g=r,o="
    line: 'shared.loader="${catalina.base}/shared","${catalina.base}/shared/*.jar"'
    regexp: "^shared.loader="
    state: present
  notify: Restart Tomcat

- name: Show ServerInfo on Errors
  become: true
  file:
    path: "{{ tomcat_catalina_base ~ '/lib/org/apache/catalina/util/ServerInfo.properties' }}"
    state: absent
  when: not (tomcat_secure_serverinfo_hide | bool)
  notify: Restart Tomcat

- name: Hide ServerInfo on Errors
  become: true
  copy:
    content: |
      server.info={{ tomcat_secure_serverinfo }}
    dest: "{{ tomcat_catalina_base ~ '/lib/org/apache/catalina/util/ServerInfo.properties' }}"
    group: "{{ tomcat_group }}"
    owner: root
    mode: "u=rw,g=r,o="
  when: tomcat_secure_serverinfo_hide | bool
  notify: Restart Tomcat

- block:
    - name: create setenv.sh
      become: true
      file:
        path: "{{ tomcat_catalina_base }}/bin/setenv.sh"
        group: root
        owner: root
        mode: "u=rw,g=r,o=r"
        state: touch

    # Classpath can only be configured in setenv.sh
    - name: setenv.sh classpath settings
      become: true
      lineinfile:
        path: "{{ tomcat_catalina_base }}/bin/setenv.sh"
        group: root
        owner: root
        mode: "u=rw,g=r,o=r"
        create: true
        backrefs: true
        regexp: "^CLASSPATH=.*$"
        line: CLASSPATH="{{ tomcat_catalina_classpath | join(':') }}"
        state: present
      notify: Restart Tomcat
  when: tomcat_catalina_classpath | length > 0
