---
- name: OS Specific Vars
  include_vars: "{{ item }}"
  with_first_found:
    - "distro-{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
    - "family-{{ ansible_os_family | lower }}.yml"

- include: install.yml
- include: configure.yml
- include: log4j2.yml
  when: tomcat_log4j2_enable | bool
- include: service.yml
