---
- hosts: all
  roles:
    - geerlingguy.java
  pre_tasks:
    # CentOS provides epel-release package, use that
    - name: Install epel
      package:
        name:
          - epel-release
          - cronie
      when: ansible_os_family | lower == 'redhat'
